---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: imagetagger
commonLabels:
  app: imagetagger

resources:
  - k8s/namespace.yml
  - k8s/postgres.yml
  - k8s/web_app.yml

configMapGenerator:
  - name: imagetagger-web
    files:
      - "settings.py=./imagetagger/imagetagger/settings.py.example"
  - name: imagetagger-postgres
    literals:
      - "POSTGRES_PASSWORD=imagetagger"
      - "POSTGRES_USER=imagetagger"
      - "POSTGRES_DB=imagetagger"
